apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  APP_ENV: local
  APP_DEBUG: "true"
  APP_KEY: SomeRandomKey!!!
  APP_LOCALE: en
  APP_FALLBACK_LOCALE: en
  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_PORT: "3308"
  DB_DATABASE: homestead
  DB_USERNAME: pranav
  DB_PASSWORD: Zxcvbnm.123
  CACHE_DRIVER: memcached
  SESSION_DRIVER: memcached
  QUEUE_DRIVER: database
  MAIL_DRIVER: mailgun
  MAILGUN_DOMAIN: <your-mailgun-domain>
  MAILGUN_SECRET: <your-mailgun-api-key>
