version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    env_file:
      - .env.example
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Zxcvbnm.123
      MYSQL_DATABASE: homestead
      MYSQL_USER: 'pranav'
      MYSQL_PASSWORD: 'Zxcvbnm.123'
    ports:
      - "3308:3306"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    depends_on:
      - app
