version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/html
    env_file:
      - .env.example  # Load environment variables from .env.example file
    depends_on:
      - mysql  # Ensure MySQL container runs first

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Zxcvbnm.123
      MYSQL_DATABASE: homestead
    ports:
      - "3306:3306"
