apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: local-files-nginx
              mountPath: /etc/nginx/nginx.conf
      volumes:
        - name: local-files-nginx
          hostPath:
            path: /run/desktop/mnt/host/c/Users/Softsuave_PC/Documents/GitHub/brush-lumen-mysql/nginx/nginx.conf
            type: File
